Group7A2/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Group7A2.Models
{
    public class Post
    {
        private DateTime _date = DateTime.Now;

        public virtual int PostId { get; set; }
        [Required(ErrorMessage = "What is your topic?")]
        [StringLength(100, MinimumLength = 2)]
        public virtual String Subject { get; set; }

        [Required(ErrorMessage = "Give us more details about your topic.")]
        [StringLength(500, MinimumLength = 10)]
        [DataType(DataType.MultilineText)]
        public virtual String Content { get; set; }

        public virtual int CategoryId { get; set; }

        public virtual Category Category { get; set; }

        public virtual String Author { get; set; }

        //Set PostTime dafault value.
        public DateTime PostTime
        {
            get { return _date; }
            set { _date = value; }
        }

        //A post may has zero or more comments
        public virtual List<Comment> Comments { get; set; }
    }
}

Group7A2/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Group7A2.Models;

namespace Group7A2.Controllers
{
    [RequireHttps]
    public class CommentsController : Controller
    {
        ICommentRepository db;

        public CommentsController()
        {
            this.db = new EFDataComments();
        }
        //If the contrustor pass in parameter, will use mock date, mean it is for testing.
        public CommentsController(ICommentRepository mockDb)
        {
            this.db = mockDb;
        }

        // GET: Comments
        //public ActionResult Index()
        //{
        //    var comments = db.Comments.Include(c => c.Post);
        //    return View(comments.ToList());
        //}

        // GET: Comments/Details/5
        //public ActionResult Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    //Comment comment = db.Comments.Find(id);
        //    Comment comment = db.Comments.SingleOrDefault(c => c.CommentId == id);
        //    if (comment == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(comment);
        //}

        //GET: Comments/Create
       //[Authorize]
       // public ActionResult Create()
       // {
       //     ViewBag.PostId = new SelectList(db.Posts, "PostId", "Subject");
       //     return View("Create");
       // }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize]
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "CommentId,Content,PostId")] Comment comment)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        comment.Author = User.Identity.Name;
        //        //db.Comments.Add(comment);
        //        //db.SaveChanges();
        //        int postId = comment.PostId;
        //        db.Save(comment);
        //        return PartialView("Details", comment);
        //    }

        //    ViewBag.PostId = new SelectList(db.Posts, "PostId", "Subject", comment.PostId);
        //    return PartialView("Create", comment);
        //}

        // GET: Comments/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return View("Error");
            }
            //Comment comment = db.Comments.Find(id);
            Comment comment = db.Comments.SingleOrDefault(c => c.CommentId == id);
            if (comment == null)
            {
                //return HttpNotFound();
                return View("Error");
            }
            ViewBag.PostId = new SelectList(db.Posts, "PostId", "Subject", comment.PostId);
            return View("Edit", comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CommentId,Content,PostId,Author,PostTime")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(comment).State = EntityState.Modified;
                //db.SaveChanges();
                db.Save(comment);
                int postId = comment.PostId;
                return RedirectToAction("Details", "Posts", new { id = postId });
            }
            ViewBag.PostId = new SelectList(db.Posts, "PostId", "Subject", comment.PostId);
            
            return View("Edit", comment);
            
        }

        // GET: Comments/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return View("Error");
            }
            //Comment comment = db.Comments.Find(id);
            Comment comment = db.Comments.SingleOrDefault(c => c.CommentId == id);
            if (comment == null)
            {
                //return HttpNotFound();
                return View("Error");
            }
            return View(comment);
        }

        // POST: Comments/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            //Comment comment = db.Comments.Find(id);
            Comment comment = db.Comments.SingleOrDefault(c => c.CommentId == id);
            //db.Comments.Remove(comment);
            //db.SaveChanges();
            db.Delete(comment);
            int postId = comment.PostId;
            return RedirectToAction("Details", "Posts", new { id = postId });
        }
         
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Group7A2/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Group7A2.Models;

namespace Group7A2.Controllers
{
    [RequireHttps]
    public class PostsController : Controller
    {

        IPostRepository db;

        public PostsController()
        {
            this.db = new EFDataPosts();
        }
        //If the contrustor pass in parameter, will use mock date, mean it is for testing.
        public PostsController(IPostRepository mockDb)
        {
            this.db = mockDb;
        }

        // GET: PostsEFDataPosts
        //public ActionResult Index()
        //{
        //    var posts = db.Posts.Include(p => p.Category);
        //    return View(posts.ToList());
        //}

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return View("Error");
            }
            PostCommentViewModel postComment = new PostCommentViewModel();
            postComment.post = db.Posts.SingleOrDefault(c => c.PostId == id);
            //postComment.post.Comments = db.Comments.OrderByDescending(p => p.PostTime.Date).ThenBy(p => p.PostTime.TimeOfDay).ToList();
            
            //Post post = db.Posts.SingleOrDefault(c => c.PostId == id);
            if (postComment.post == null)
            {
                //return HttpNotFound();
                return View("Error");
            }
            postComment.post.Comments = postComment.post.Comments.OrderByDescending(p => p.PostTime.Date).ThenBy(p => p.PostTime.TimeOfDay).ToList();
            return View("Details",postComment);
        }


        // GET: Posts/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name");
            return View("Create");
        }

        // POST: Posts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "PostId,Subject,Content,CategoryId")] Post post)
        {
            if (ModelState.IsValid)
            {
                post.Author = User.Identity.Name;
                db.Save(post);
                //db.SaveChanges();
                //return RedirectToAction("Create");
                return RedirectToAction("PostList", "Categories", new { id = post.CategoryId });
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", post.CategoryId);
            return View("Create", post);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateComment([Bind(Include = "CommentId,Content,PostId")] Comment newComment)
        {
            PostCommentViewModel pc = new PostCommentViewModel();
            int id = newComment.PostId;
            if (ModelState.IsValid)
            {

                newComment.Author = User.Identity.Name;
                //db.Comments.Add(comment);
                //db.SaveChanges();
                
                db.Save(newComment);
                pc.post = db.Posts.SingleOrDefault(c => c.PostId == id);
                pc.post.Comments = pc.post.Comments.OrderByDescending(p => p.PostTime.Date).ThenBy(p => p.PostTime.TimeOfDay).ToList();
                ModelState.Clear();
                return PartialView("Details", pc);
            }

            pc.post = db.Posts.SingleOrDefault(c => c.PostId == id);
            return PartialView("Details", pc);
        }

        // GET: Posts/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return View("Error");
            }
            Post post = db.Posts.SingleOrDefault(c => c.PostId == id);
            if (post == null)
            {
                //return HttpNotFound();
                return View("Error");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", post.CategoryId);
            return View("Edit", post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "PostId,Subject,Content,CategoryId")] Post post)
        {
            if (ModelState.IsValid)
            {
                post.Author = User.Identity.Name;
                //db.Entry(post).State = EntityState.Modified;
                //db.SaveChanges();
                db.Save(post);
                return RedirectToAction("Details", new { id = post.PostId});
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", post.CategoryId);
            return View("Edit", post);
        }

        // GET: Posts/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return View("Error");
            }
            Post post = db.Posts.SingleOrDefault(c => c.PostId == id);
            if (post == null)
            {
                //return HttpNotFound();
                return View("Error");
            }
            return View("Delete", post); 
            
        }

        // POST: Posts/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            Post post = db.Posts.SingleOrDefault(c => c.PostId == id);
            
            if (post == null)
            {
                return View("Error");
            }
            int categoryId = post.CategoryId;
            db.Delete(post);
            return RedirectToAction("PostList", "Categories", new { id = categoryId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Group7A2/Views/Posts/Create.cshtml
@model Group7A2.Models.Post

@{
    ViewBag.Title = "Create a post";
}

<h2>Write a post!</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })

            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostTime, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Group7A2/Views/Posts/Delete.cshtml
@model Group7A2.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostTime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Group7A2/Views/Posts/Details.cshtml
@model Group7A2.Models.PostCommentViewModel

@{
    ViewBag.Title = "Details";
}
<div id="MainBody">
    <div class="container">
        <h4>Back to @Html.ActionLink(Model.post.Category.Name, "PostList", "Categories", new { id = Model.post.CategoryId }, null)</h4>
    </div>



    <div class="container">
        <h2>@Html.DisplayFor(model => model.post.Subject)</h2>
        <p>Post By: @Html.DisplayFor(model => model.post.Author) </p>
        <p>@Html.DisplayFor(model => model.post.PostTime)</p>
        <hr />
        <p>@Html.DisplayFor(model => model.post.Content)</p>
        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.post.PostId })
        }
        @if (User.IsInRole("Admin"))
        {
            @Html.ActionLink("Delete", "Delete", new { id = Model.post.PostId })
        }
        <hr />
        @foreach (var com in Model.post.Comments)
        {
            <div class="col-md-12  jumbotron-fluid mt-5 bg-light pl-3">
                <p>@Html.DisplayFor(modelItem => com.Content)</p>
                <p>Comment By: @Html.DisplayFor(modelItem => com.Author)</p>
                <p>@Html.DisplayFor(modelItem => com.PostTime)</p>
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Edit this comment", "Edit", "Comments", new { id = com.CommentId }, null)
                }
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Delete this comment", "Delete", "Comments", new { id = com.CommentId }, null)
                }
                <hr />
            </div>
        }

        <hr />

        @using (Ajax.BeginForm("CreateComment", "Posts", new AjaxOptions
        {
            InsertionMode = InsertionMode.Replace,
            HttpMethod = "POST",
            UpdateTargetId = "MainBody",
        }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.newComment.Content, "Add a comment:", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.newComment.Content, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.newComment.Content, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.Hidden("newComment.PostId", Model.post.PostId)
            </div>

            @if (User.Identity.IsAuthenticated)
            {
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                </div>
            }
            else
            {
                <h4> To comment on this post, please @Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</h4>
            }
        </div>

        }

    </div>
</div>

Group7A2/Views/Posts/Edit.cshtml
@model Group7A2.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PostId)

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>
       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Group7A2/Views/Posts/Index.cshtml
@model IEnumerable<Group7A2.Models.PostViewModel>

@{
    ViewBag.Title = "Index";
}

<div class="container" >
    @foreach (var item in Model)
    {
        <div class="col-md-12  jumbotron-fluid ">
            <h3>@Html.DisplayFor(modelItem => item.Name)</h3>
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Edit", "Edit", new { id = item.CategoryId })
            }
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Details", "Details", new { id = item.CategoryId })
            }
            @if (User.IsInRole("Admin"))
            {
                @Html.ActionLink("Delete", "Delete", new { id = item.CategoryId })}
            <p> @Html.DisplayFor(modelItem => item.Description)</p>
            <button class="btn btn-secondary">@Html.ActionLink("Get More", "Index", "Posts", new { id = item.CategoryId }) >></button>
        </div>
    }

</div>

@*<h2>Index</h2>*@

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Content)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PostTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Subject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Content)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PostTime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PostId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PostId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PostId })
        </td>
    </tr>
}

</table>*@