Group7A2/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Group7A2.Models;

namespace Group7A2.Controllers
{
    [RequireHttps]
    public class PostsController : Controller
    {

        IPostRepository db;

        public PostsController()
        {
            this.db = new EFDataPosts();
        }
        //If the contrustor pass in parameter, will use mock date, mean it is for testing.
        public PostsController(IPostRepository mockDb)
        {
            this.db = mockDb;
        }

        // GET: PostsEFDataPosts
        //public ActionResult Index()
        //{
        //    var posts = db.Posts.Include(p => p.Category);
        //    return View(posts.ToList());
        //}

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return View("Error");
            }
            PostCommentViewModel postComment = new PostCommentViewModel();
            postComment.post = db.Posts.SingleOrDefault(c => c.PostId == id);
            //postComment.post.Comments = db.Comments.OrderByDescending(p => p.PostTime.Date).ThenBy(p => p.PostTime.TimeOfDay).ToList();
            
            //Post post = db.Posts.SingleOrDefault(c => c.PostId == id);
            if (postComment.post == null)
            {
                //return HttpNotFound();
                return View("Error");
            }
            postComment.post.Comments = postComment.post.Comments.OrderByDescending(p => p.PostTime.Date).ThenBy(p => p.PostTime.TimeOfDay).ToList();
            return View("Details",postComment);
        }


        // GET: Posts/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name");
            return View("Create");
        }

        // POST: Posts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Create([Bind(Include = "PostId,Subject,Content,CategoryId")] Post post)
        {
            if (ModelState.IsValid)
            {
                post.Author = User.Identity.Name;
                db.Save(post);
                //db.SaveChanges();
                //return RedirectToAction("Create");
                return RedirectToAction("PostList", "Categories", new { id = post.CategoryId });
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", post.CategoryId);
            return View("Create", post);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateComment([Bind(Include = "CommentId,Content,PostId")] Comment newComment)
        {
            PostCommentViewModel pc = new PostCommentViewModel();
            int id = newComment.PostId;
            if (ModelState.IsValid)
            {

                newComment.Author = User.Identity.Name;
                //db.Comments.Add(comment);
                //db.SaveChanges();
                
                db.Save(newComment);
                pc.post = db.Posts.SingleOrDefault(c => c.PostId == id);
                pc.post.Comments = pc.post.Comments.OrderByDescending(p => p.PostTime.Date).ThenBy(p => p.PostTime.TimeOfDay).ToList();
                ModelState.Clear();
                return PartialView("Details", pc);
            }

            pc.post = db.Posts.SingleOrDefault(c => c.PostId == id);
            return PartialView("Details", pc);
        }

        // GET: Posts/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return View("Error");
            }
            Post post = db.Posts.SingleOrDefault(c => c.PostId == id);
            if (post == null)
            {
                //return HttpNotFound();
                return View("Error");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", post.CategoryId);
            return View("Edit", post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit([Bind(Include = "PostId,Subject,Content,CategoryId")] Post post)
        {
            if (ModelState.IsValid)
            {
                post.Author = User.Identity.Name;
                //db.Entry(post).State = EntityState.Modified;
                //db.SaveChanges();
                db.Save(post);
                return RedirectToAction("Details", new { id = post.PostId});
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "CategoryId", "Name", post.CategoryId);
            return View("Edit", post);
        }

        // GET: Posts/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return View("Error");
            }
            Post post = db.Posts.SingleOrDefault(c => c.PostId == id);
            if (post == null)
            {
                //return HttpNotFound();
                return View("Error");
            }
            return View("Delete", post); 
            
        }

        // POST: Posts/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {

            Post post = db.Posts.SingleOrDefault(c => c.PostId == id);
            
            if (post == null)
            {
                return View("Error");
            }
            int categoryId = post.CategoryId;
            db.Delete(post);
            return RedirectToAction("PostList", "Categories", new { id = categoryId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Group7A2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Georgian College Student Forum</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/style/AddStyle.css")
    @Scripts.Render("~/bundles/modernizr")
    


</head>
<body>

    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("","", "")">
                <img src="~/Content/images/georgian-college-experience-logo.svg" width="120" height="80" alt="" />
            </a>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pt-5">
                    <li class="nav-item">@Html.ActionLink("What's New", "", "Home")</li>
                    <li class="nav-item">@Html.ActionLink("Create A Post", "Create", "Posts")</li>
                    <li class="nav-item">@Html.ActionLink("Contact Us", "Contact", "Home")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Make your campus life a little easier</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>*@
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>